import * as fs from 'fs';
import * as mime from 'mime';
import BuiltInternalResourcesList from "../build/internal-resources.json"; // At live, this file is generated by the finalize-build script

const importDir = require('directory-import');
const externalResourcesImport = importDir({ directoryPath: './external' });

const externalResources = Object.keys(externalResourcesImport).reduce((acc, key) => { 
    const resourceKey = key.replace('/', '').replace(/\.js$/, '');
    const resource = externalResourcesImport[key].default;
    
    return {
        ...acc,
        [resourceKey]: resource,
    };
}, {});

export const InternalResources = {
    localResourcesPath: './src/resources/internal',
    listResources(includeIndexHtml: boolean = false): string[] {
        const resourcesList = BuiltInternalResourcesList.length > 0 ? BuiltInternalResourcesList : fs.readdirSync(this.localResourcesPath);
        if (includeIndexHtml) {
            return resourcesList;
        }
        return resourcesList.filter((resourceFilename: string) => resourceFilename !== 'index.html');
    },
    async getResourcePassThrough(resourceURI: string): Promise<{ body: string, mime: string | null } | undefined> {
        try {
            const resourceFilename = resourceURI.replace('/', '');
            const filePath = `${this.localResourcesPath}/${resourceFilename}`;
            return {
                body: await fs.promises.readFile(filePath, 'utf8'),
                mime: mime.getType(filePath),
            };
        } catch (error) {}
        return;
    }
}

export default {
    ...externalResources,
};