version: "3.8"

services:
  app:
    image: node:18-alpine
    user: node
    command: sh -c "npm install && npm run start"
    working_dir: /app
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - 3166:3166
    networks:
      - vfd-network

networks:
  vfd-network:
    driver: bridge
    external: true