version: "3.8"

services:
  codesets:
    image: node:18-alpine
    user: node
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    volumes:
      - .:/app
      - ./src/build/environment.docker-compose.json:/app/src/build/environment.json
    stdin_open: true
    tty: true
    ports:
      - 3166:3166
    networks:
      - vfd-network
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    labels:
      - traefik.http.routers.codesets.rule=Host(`codesets.localhost`)

networks:
  vfd-network:
    driver: bridge
    external: true
