name: "Dev: build, test and deploy"
on:
  push:
    branches: ["main"]

jobs:
  deploy-dev:
    uses: Virtual-Finland-Development/codesets/.github/workflows/build-test-deploy.yml@main
    secrets: inherit
    with:
      environment: dev
